<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Admin_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get admin by id
     */
    function get_admin($id)
    {
        return $this->db->get_where('Admin',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all admin
     */
    function get_all_admin()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('Admin')->result_array();
    }
        
    /*
     * function to add new admin
     */
    function add_admin($params)
    {
        $this->db->insert('Admin',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update admin
     */
    function update_admin($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('Admin',$params);
    }
    
    /*
     * function to delete admin
     */
    function delete_admin($id)
    {
        return $this->db->delete('Admin',array('id'=>$id));
    }
}
