<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Doku_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get doku by id
     */
    function get_doku($id)
    {
        return $this->db->get_where('doku',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all doku
     */
    function get_all_doku()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('doku')->result_array();
    }
        
    /*
     * function to add new doku
     */
    function add_doku($params)
    {
        $this->db->insert('doku',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update doku
     */
    function update_doku($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('doku',$params);
    }
    
    /*
     * function to delete doku
     */
    function delete_doku($id)
    {
        return $this->db->delete('doku',array('id'=>$id));
    }
}
